use_frameworks!

target 'NSDecimalNumberTool_Example' do
  pod 'NSDecimalNumberTool', :path => '../'

  target 'NSDecimalNumberTool_Tests' do
    inherit! :search_paths

#https://github.com/YuanJiaShuai/YJSSpecs.git
  end
end
